production.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include `production.h`
#include <math.h>
#include <string.h>
Functions
bool production (int argc, char *argv[])
void PlayOne (unsigned int nr, unsigned int nc, char *Old, char *New)
void usage (void)
char getLetter (int row, int col, int nCols, char *Old)
int howManyNeighbors (int row, int col, int nRows, int nCols, char *Old)
void fileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char *ar_p, FILE *fp)
int generate (int gens, int nRows, int nCols, char *nextGen_p, char *curr_p, char *beforeCurr_p, char print, char pause)
bool anyX (char *arr, int nRows, int nCols)
bool sameContent (char *one_p, char *another_p, int nRows, int nCols)
void printThis (int nRows, int nCols, char *nextGen_p)
Function Documentation
anyX()
bool anyX (char * arr, int nRows, int nCols)
anyX Looks through a game board (multi-dimensional array) and determines if there is any living cells (`X`)
Parameters
char* arr The pointer to the array that is being searched
int nRows The number of rows in the array
int nCols The number of columns in the array
Returns
bool returns a boolean, true or false, whether there is a living cell in the array or not
References getLetter().
Referenced by generate(), testAnyX(), and testAnyX2().
fileIntoArray()
void fileIntoArray (int nRows, int nCols, int howManyLinesInFile, int maximumWidth, char * ar_p, FILE * fp)
fileIntoArray takes the given pattern file and translates it into a multidimensional array
Parameters
int nRows The number of rows in the array
int nCols The number of columns in the array
int howManyLinesInFile The number of lines that are in the input pattern file
int maximumWidth The number of columns in the file
char* ar_p The pointer to the array that will be created from the file
FILE* fp The pointer to the file
Returns
There is no return because the results are in ar_p
Referenced by production().
generate()
int generate (int gens, int nRows, int nCols, char * nextGen_p, char * curr_p, char * beforeCurr_p, char print, char pause)
generate Plays through the number of generations requested
Parameters
int gens The number of generations that the function should play
int nRows The number of rows in the array
int nCols The number of columns in the array
char* nextGen_p The pointer to the array for the next generation created
char* curr_p The pointer to the array of the current generation we are on
char* beforeCurr_p The pointer to the array of the previous generation
char print This is the character that is inputted by the user that decides if the program should print after every generation
char pause This is the character that decides if the program should pause after every generation
Returns
int The number of generations played
References anyX(), PlayOne(), printThis(), and sameContent().
Referenced by production().
getLetter()
char getLetter (int row, int col, int nCols, char * Old)
getLetter Finds whether there is a living (`X`) OR dead (`o`) cell in a certain position
Parameters
int row This is the row of the desired position
int col This is the column of the desired position
int nCols This is the number of columns in the multi-dimensional array
char* Pointer to the array that contains the board
Returns
char This function returns the character that is locacted in the desired location
Referenced by anyX(), howManyNeighbors(), PlayOne(), printThis(), and sameContent().
howManyNeighbors()
int howManyNeighbors (int row, int col, int nRows, int nCols, char * Old)
howManyNeighbors Checks to see how many living cells are neighboring a desired cell
Parameters
int row The row of the cell we are looking for
int col The column of the cell we are looking for
int nRows The number of rows in the array
int nCols The number of columns in the array
char* Pointer to the array that contains the board
Returns
int Returns the number of living neighbor cells that a cell has
References getLetter().
Referenced by PlayOne(), testhowManyNeighbors(), and testhowManyNeighbors2().
PlayOne()
void PlayOne (unsigned int nr, unsigned int nc, char * Old, char * New)
PlayOne carries out one generation
Parameters
unsigned int nr, the number of rows in the petri dish
unsigned int nc, the number of columns in the petri dish
char* Old, the location of the upper left of starting petri dish
char* New, the location of the upper left of the ending petri dish
Returns
There is none, because results are in New array
References getLetter(), and howManyNeighbors().
Referenced by generate(), testPlayBlockOne(), testPlayOne(), testPlayOneAllDie(), and testPlayOneBlinker().
printThis()
void printThis (int nRows, int nCols, char * nextGen_p)
printThis Prints out the gameboard with the appropriate living and dead cells in their correct position
Parameters
int nRows The number of rows that will be in the printed array
int nCols The number of columns that will be in the printer array
char* nextGen_p The pointer to the array of the next generation to be printed
Returns
void Returns nothing because the gameboard will be printed in nextGen_p
References getLetter().
Referenced by generate().
production()
bool production (int argc, char * argv[])
production Takes in the user input
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line
Returns
true if program was able to play the Game Of Life false if user entered bad input or something went wrong
References fileIntoArray(), generate(), and usage().
Referenced by main().
sameContent()
bool sameContent (char * one_p, char * another_p, int nRows, int nCols)
sameContent Compares two gameboards and determines if they have the same patttern or not
Parameters
char* one_p This is the pointer to the array for a gameboard
char* another_p This is the pointer to the array for another gameboard being compared to the first one
int nRows The number of rows in the array
int nCols The number of columns in the array
Returns
bool returns true if the two gameboards have the same pattern and false if they're different
References getLetter().
Referenced by generate(), testsameContent(), and testsameContent2().
usage()
void usage (void)
usage This function outputs an error message when the user enters a bad input
Returns
void There is no return becuase it prints out an error message
Referenced by production().