tests.c File Reference
#include <stdbool.h>
#include `tests.h`
#include `production.h`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
bool tests (void)
bool testReadInput (void)
bool testMakeArrays (void)
bool testPlayOne (void)
bool testPlayOneBlinker (void)
bool testPlayBlockOne (void)
bool testPlayOneAllDie (void)
bool testhowManyNeighbors (void)
bool testhowManyNeighbors2 (void)
bool testAnyX (void)
bool testAnyX2 (void)
bool testsameContent (void)
bool testsameContent2 (void)
Function Documentation
testAnyX()
bool testAnyX (void)
References anyX().
Referenced by tests().
testAnyX2()
bool testAnyX2 (void)
References anyX().
Referenced by tests().
testhowManyNeighbors()
bool testhowManyNeighbors (void)
References howManyNeighbors().
Referenced by tests().
testhowManyNeighbors2()
bool testhowManyNeighbors2 (void)
References howManyNeighbors().
Referenced by tests().
testMakeArrays()
bool testMakeArrays (void)
Referenced by tests().
testPlayBlockOne()
bool testPlayBlockOne (void)
References PlayOne().
Referenced by tests().
testPlayOne()
bool testPlayOne (void)
References PlayOne().
Referenced by tests().
testPlayOneAllDie()
bool testPlayOneAllDie (void)
References PlayOne().
Referenced by tests().
testPlayOneBlinker()
bool testPlayOneBlinker (void)
References PlayOne().
Referenced by tests().
testReadInput()
bool testReadInput (void)
Referenced by tests().
tests()
bool tests (void)
References testAnyX(), testAnyX2(), testhowManyNeighbors(), testhowManyNeighbors2(), testMakeArrays(), testPlayBlockOne(), testPlayOne(), testPlayOneAllDie(), testPlayOneBlinker(), testReadInput(), testsameContent(), and testsameContent2().
Referenced by main().
testsameContent()
bool testsameContent (void)
References sameContent().
Referenced by tests().
testsameContent2()
bool testsameContent2 (void)
References sameContent().
Referenced by tests().